"""
Context stream — AllScale API client (sponsor track).

Owned by: Stream 3 (Context)
Do NOT edit this file if you are on the Brain or Muscle stream.
"""

from __future__ import annotations


async def trigger_bounty_payout(wallet_address: str, amount: float) -> bool:
    """
    Trigger an automated bounty payout via the AllScale API.

    Called by the Brain stream when a confirmed vulnerability is found and
    the scan result has ``status == "success"`` with non-empty findings.
    The result is stored in ``PRScanState.bounty_paid``.

    Reads ``ALLSCALE_API_KEY`` from the environment.

    Args:
        wallet_address: The recipient's wallet address for the payout.
        amount: The payout amount (in the currency/token defined by AllScale).

    Returns:
        True if the payout was successfully triggered, False otherwise.
    """
    pass
