"""
Context stream — AllScale API client (sponsor track).

Owned by: Stream 3 (Context)
Do NOT edit this file if you are on the Brain or Muscle stream.
"""

from __future__ import annotations

import logging
import os

import httpx
from dotenv import load_dotenv
from tenacity import (
    retry,
    retry_if_exception,
    stop_after_attempt,
    wait_exponential,
)

load_dotenv()

logger = logging.getLogger(__name__)

_ALLSCALE_API = "https://api.allscale.io/v1"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _is_retryable(exc: BaseException) -> bool:
    if isinstance(exc, httpx.HTTPStatusError):
        return exc.response.status_code in {429, 502, 503}
    return isinstance(exc, (httpx.TimeoutException, httpx.NetworkError))


_retry = retry(
    retry=retry_if_exception(_is_retryable),
    wait=wait_exponential(multiplier=1, min=1, max=10),
    stop=stop_after_attempt(3),
    reraise=True,
)


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------


async def trigger_bounty_payout(wallet_address: str, amount: float) -> bool:
    """
    Trigger an automated bounty payout via the AllScale API.

    Called by the Brain stream when a confirmed vulnerability is found and
    the scan result has ``status == "success"`` with non-empty findings.
    The result is stored in ``PRScanState.bounty_paid``.

    Reads ``ALLSCALE_API_KEY`` from the environment.

    Args:
        wallet_address: The recipient's wallet address for the payout.
        amount: The payout amount (in the currency/token defined by AllScale).

    Returns:
        True if the payout was successfully triggered, False otherwise.
    """
    try:
        api_key = os.getenv("ALLSCALE_API_KEY", "")
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }

        @_retry
        async def _post() -> bool:
            async with httpx.AsyncClient(timeout=30) as client:
                resp = await client.post(
                    f"{_ALLSCALE_API}/payouts",
                    headers=headers,
                    json={"wallet_address": wallet_address, "amount": amount},
                )
                resp.raise_for_status()
                return True

        return await _post()
    except Exception:
        logger.exception(
            "trigger_bounty_payout failed for wallet=%r amount=%s",
            wallet_address,
            amount,
        )
        return False
