"""
Context stream — AllScale API client (sponsor track).

Owned by: Stream 3 (Context)
Do NOT edit this file if you are on the Brain or Muscle stream.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import logging
import os
import time
import uuid
from base64 import b64encode

import httpx
from dotenv import load_dotenv
from tenacity import (
    retry,
    retry_if_exception,
    stop_after_attempt,
    wait_exponential,
)

load_dotenv()

logger = logging.getLogger(__name__)

# Correct base URL per AllScale API docs (openapi.allscale.io, not api.allscale.io)
_ALLSCALE_API = "https://openapi.allscale.io"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _is_retryable(exc: BaseException) -> bool:
    if isinstance(exc, httpx.HTTPStatusError):
        return exc.response.status_code in {429, 502, 503}
    return isinstance(exc, (httpx.TimeoutException, httpx.NetworkError))


_retry = retry(
    retry=retry_if_exception(_is_retryable),
    wait=wait_exponential(multiplier=1, min=1, max=10),
    stop=stop_after_attempt(3),
    reraise=True,
)


def _sign_request(
    method: str,
    path: str,
    body: str,
    query: str = "",
) -> dict[str, str]:
    """
    Build HMAC-SHA256 signed headers for the AllScale API.

    Canonical string format (joined with newlines):
        METHOD
        PATH
        QUERY_STRING
        TIMESTAMP
        NONCE
        BODY_SHA256
    """
    api_key = os.getenv("ALLSCALE_API_KEY", "")
    api_secret = os.getenv("ALLSCALE_API_SECRET", "")

    timestamp = str(int(time.time()))
    nonce = str(uuid.uuid4())

    body_hash = hashlib.sha256(body.encode()).hexdigest()

    canonical = "\n".join([
        method.upper(),
        path,
        query,
        timestamp,
        nonce,
        body_hash,
    ])

    signature = b64encode(
        hmac.new(
            api_secret.encode(),
            canonical.encode(),
            hashlib.sha256,
        ).digest()
    ).decode()

    return {
        "X-API-Key": api_key,
        "X-Timestamp": timestamp,
        "X-Nonce": nonce,
        "X-Signature": f"v1={signature}",
        "Content-Type": "application/json",
    }


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------


async def trigger_bounty_payout(wallet_address: str, amount: float) -> bool:
    """
    Trigger an automated bounty payout via the AllScale API.

    Creates a checkout intent for a USDC payout to the given wallet address.
    Called by the Brain stream when a confirmed vulnerability is found.
    The result is stored in ``PRScanState.bounty_paid``.

    Reads ``ALLSCALE_API_KEY`` and ``ALLSCALE_API_SECRET`` from the environment.

    Args:
        wallet_address: The recipient's wallet address for the payout.
        amount: The payout amount in USDC (e.g. 10.0 = 10 USDC).

    Returns:
        True if the checkout intent was successfully created, False otherwise.
    """
    try:
        path = "/v1/checkout_intents/"
        # AllScale amount_cents = stable-coin "cents" (1.00 USDC = 100 cents)
        # Minimum is 0.1 USDC (10 cents); floor at 11 cents to stay above limit.
        amount_cents = max(int(amount * 100), 11)

        body_payload = {
            "stable_coin": 2,           # 2 = USDC per AllScale StableCoin enum
            "amount_cents": amount_cents,
            "order_id": f"aegis-bounty-{wallet_address[:8]}",
            "order_description": f"AegisAgent vulnerability bounty payout to {wallet_address}",
            "user_id": wallet_address,
        }
        body_str = json.dumps(body_payload, separators=(",", ":"))
        headers = _sign_request("POST", path, body_str)

        @_retry
        async def _post() -> bool:
            async with httpx.AsyncClient(timeout=30) as client:
                resp = await client.post(
                    f"{_ALLSCALE_API}{path}",
                    headers=headers,
                    content=body_str,
                )
                resp.raise_for_status()
                data = resp.json()
                if data.get("code") != 0:
                    logger.error(
                        "AllScale returned non-zero code %s: %s",
                        data.get("code"),
                        data.get("error"),
                    )
                    return False
                logger.info(
                    "AllScale checkout intent created: %s",
                    data.get("payload", {}).get("allscale_checkout_intent_id"),
                )
                return True

        return await _post()
    except Exception:
        logger.exception(
            "trigger_bounty_payout failed for wallet=%r amount=%s",
            wallet_address,
            amount,
        )
        return False
