"""
Context stream — GitHub API client.

Owned by: Stream 3 (Context)
Do NOT edit this file if you are on the Brain or Muscle stream.
"""

from __future__ import annotations

PENDING_STATUS_BODY = "🛡️ AegisAgent is analyzing this PR for database impact..."
"""
Exact comment body posted by post_pending_status.

All three streams must agree on this string. It is defined here (in the
Context stream's file) as the single source of truth. The Brain stream reads
PRScanState.pending_comment_id (the int returned by post_pending_status) but
never hard-codes this string itself.
"""


async def get_pr_diff(pr_url: str) -> str:
    """
    Fetch and return the raw unified diff text for a GitHub Pull Request.

    Parses the owner, repo, and PR number from ``pr_url`` and calls the
    GitHub API. Reads ``GITHUB_TOKEN`` from the environment.

    Args:
        pr_url: Full GitHub PR URL, e.g.
            "https://github.com/owner/repo/pull/42".

    Returns:
        The unified diff as a plain string (the same text you see when you
        append ``.diff`` to a GitHub PR URL).
    """
    pass


async def post_pending_status(pr_url: str) -> int:
    """
    Post an immediate placeholder comment to the PR and return its comment ID.

    The comment body is always ``PENDING_STATUS_BODY``:
        "🛡️ AegisAgent is analyzing this PR for database impact..."

    This must be the very first action the agent takes after a PR triggers it,
    so developers see an instant response. The returned comment ID is stored
    in ``PRScanState.pending_comment_id`` and passed to ``update_pr_comment``
    at the end of the scan to replace the placeholder with final results.

    Args:
        pr_url: Full GitHub PR URL, e.g.
            "https://github.com/owner/repo/pull/42".

    Returns:
        The integer GitHub comment ID of the newly created comment.
    """
    pass


async def update_pr_comment(comment_id: int, comment_body: str) -> bool:
    """
    Edit an existing PR comment in-place with new body text.

    Called at the end of the orchestration flow to replace the pending-status
    message (posted by ``post_pending_status``) with the final LLM-simplified
    vulnerability report. This keeps the PR thread clean — one comment that
    evolves rather than a wall of bot messages.

    Args:
        comment_id: The GitHub comment ID returned by ``post_pending_status``
            (stored in ``PRScanState.pending_comment_id``).
        comment_body: The new Markdown body to set on the comment (the
            LLM-simplified vulnerability summary).

    Returns:
        True if the update succeeded, False otherwise.
    """
    pass


async def post_pr_comment(pr_url: str, comment_body: str) -> bool:
    """
    Post a net-new comment on a Pull Request.

    Fallback for cases where a genuinely new comment is needed (e.g., a
    re-scan triggered later). For the primary scan result, always prefer
    ``update_pr_comment`` to keep the thread clean.

    Args:
        pr_url: Full GitHub PR URL.
        comment_body: Markdown body of the comment to post.

    Returns:
        True if the comment was posted successfully, False otherwise.
    """
    pass
