"""
Context stream — GitHub API client.

Owned by: Stream 3 (Context)
Do NOT edit this file if you are on the Brain or Muscle stream.
"""

from __future__ import annotations

import logging
import os
import re
from urllib.parse import urlparse

import httpx
from dotenv import load_dotenv
from tenacity import (
    retry,
    retry_if_exception,
    stop_after_attempt,
    wait_exponential,
)

load_dotenv()

logger = logging.getLogger(__name__)

PENDING_STATUS_BODY = "🛡️ AegisAgent is analyzing this PR for database impact..."
"""
Exact comment body posted by post_pending_status.

All three streams must agree on this string. It is defined here (in the
Context stream's file) as the single source of truth. The Brain stream reads
PRScanState.pending_comment_id (the int returned by post_pending_status) but
never hard-codes this string itself.
"""

_GITHUB_API = "https://api.github.com"

# Maps comment_id → (owner, repo) so update_pr_comment can build the URL
# without needing the original PR URL (which is not in its signature).
_comment_repo_cache: dict[int, tuple[str, str]] = {}


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _parse_pr_url(pr_url: str) -> tuple[str, str, int]:
    """Return (owner, repo, pr_number) from any GitHub PR URL variant."""
    parsed = urlparse(pr_url)
    clean = f"{parsed.scheme}://{parsed.netloc}{parsed.path}"
    m = re.search(r"github\.com/([^/]+)/([^/]+)/pull/(\d+)", clean)
    if not m:
        raise ValueError(f"Cannot parse PR URL: {pr_url!r}")
    return m.group(1), m.group(2), int(m.group(3))


def _github_headers(accept: str = "application/vnd.github+json") -> dict[str, str]:
    token = os.getenv("GITHUB_TOKEN", "")
    return {
        "Authorization": f"Bearer {token}",
        "Accept": accept,
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _is_retryable(exc: BaseException) -> bool:
    if isinstance(exc, httpx.HTTPStatusError):
        return exc.response.status_code in {429, 502, 503}
    return isinstance(exc, (httpx.TimeoutException, httpx.NetworkError))


_retry = retry(
    retry=retry_if_exception(_is_retryable),
    wait=wait_exponential(multiplier=1, min=1, max=10),
    stop=stop_after_attempt(3),
    reraise=True,
)


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------


async def get_pr_diff(pr_url: str) -> str:
    """
    Fetch and return the raw unified diff text for a GitHub Pull Request.

    Parses the owner, repo, and PR number from ``pr_url`` and calls the
    GitHub API. Reads ``GITHUB_TOKEN`` from the environment.

    Args:
        pr_url: Full GitHub PR URL, e.g.
            "https://github.com/owner/repo/pull/42".

    Returns:
        The unified diff as a plain string (the same text you see when you
        append ``.diff`` to a GitHub PR URL).
    """
    try:
        owner, repo, pr_number = _parse_pr_url(pr_url)

        @_retry
        async def _fetch() -> str:
            async with httpx.AsyncClient(timeout=30) as client:
                resp = await client.get(
                    f"{_GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}",
                    headers=_github_headers("application/vnd.github.v3.diff"),
                )
                resp.raise_for_status()
                return resp.text

        return await _fetch()
    except Exception:
        logger.exception("get_pr_diff failed for %s", pr_url)
        return ""


async def post_pending_status(pr_url: str) -> int:
    """
    Post an immediate placeholder comment to the PR and return its comment ID.

    The comment body is always ``PENDING_STATUS_BODY``:
        "🛡️ AegisAgent is analyzing this PR for database impact..."

    This must be the very first action the agent takes after a PR triggers it,
    so developers see an instant response. The returned comment ID is stored
    in ``PRScanState.pending_comment_id`` and passed to ``update_pr_comment``
    at the end of the scan to replace the placeholder with final results.

    Args:
        pr_url: Full GitHub PR URL, e.g.
            "https://github.com/owner/repo/pull/42".

    Returns:
        The integer GitHub comment ID of the newly created comment.
    """
    try:
        owner, repo, pr_number = _parse_pr_url(pr_url)

        @_retry
        async def _post() -> int:
            async with httpx.AsyncClient(timeout=30) as client:
                resp = await client.post(
                    f"{_GITHUB_API}/repos/{owner}/{repo}/issues/{pr_number}/comments",
                    headers=_github_headers(),
                    json={"body": PENDING_STATUS_BODY},
                )
                resp.raise_for_status()
                return int(resp.json()["id"])

        comment_id = await _post()
        _comment_repo_cache[comment_id] = (owner, repo)
        return comment_id
    except Exception:
        logger.exception("post_pending_status failed for %s", pr_url)
        return 0


async def update_pr_comment(comment_id: int, comment_body: str) -> bool:
    """
    Edit an existing PR comment in-place with new body text.

    Called at the end of the orchestration flow to replace the pending-status
    message (posted by ``post_pending_status``) with the final LLM-simplified
    vulnerability report. This keeps the PR thread clean — one comment that
    evolves rather than a wall of bot messages.

    Args:
        comment_id: The GitHub comment ID returned by ``post_pending_status``
            (stored in ``PRScanState.pending_comment_id``).
        comment_body: The new Markdown body to set on the comment (the
            LLM-simplified vulnerability summary).

    Returns:
        True if the update succeeded, False otherwise.
    """
    try:
        cached = _comment_repo_cache.get(comment_id)
        if cached is None:
            raise ValueError(
                f"No repo context cached for comment_id={comment_id}. "
                "post_pending_status must be called first."
            )
        owner, repo = cached

        @_retry
        async def _patch() -> bool:
            async with httpx.AsyncClient(timeout=30) as client:
                resp = await client.patch(
                    f"{_GITHUB_API}/repos/{owner}/{repo}/issues/comments/{comment_id}",
                    headers=_github_headers(),
                    json={"body": comment_body},
                )
                resp.raise_for_status()
                return True

        return await _patch()
    except Exception:
        logger.exception("update_pr_comment failed for comment_id=%s", comment_id)
        return False


async def post_pr_comment(pr_url: str, comment_body: str) -> bool:
    """
    Post a net-new comment on a Pull Request.

    Fallback for cases where a genuinely new comment is needed (e.g., a
    re-scan triggered later). For the primary scan result, always prefer
    ``update_pr_comment`` to keep the thread clean.

    Args:
        pr_url: Full GitHub PR URL.
        comment_body: Markdown body of the comment to post.

    Returns:
        True if the comment was posted successfully, False otherwise.
    """
    try:
        owner, repo, pr_number = _parse_pr_url(pr_url)

        @_retry
        async def _post() -> bool:
            async with httpx.AsyncClient(timeout=30) as client:
                resp = await client.post(
                    f"{_GITHUB_API}/repos/{owner}/{repo}/issues/{pr_number}/comments",
                    headers=_github_headers(),
                    json={"body": comment_body},
                )
                resp.raise_for_status()
                return True

        return await _post()
    except Exception:
        logger.exception("post_pr_comment failed for %s", pr_url)
        return False
