"""
Context stream — Greptile API client (sponsor track).

Owned by: Stream 3 (Context)
Do NOT edit this file if you are on the Brain or Muscle stream.
"""

from __future__ import annotations


async def analyze_diff_for_db_impact(repo_name: str, diff_text: str) -> bool:
    """
    Classify whether a PR diff touches database code.

    Sends the diff to the Greptile API and returns True if the diff contains
    database-impacting changes — raw SQL queries, ORM model changes, migration
    files, query-builder logic, etc. Returns False if the diff is unrelated to
    the database layer.

    Reads ``GREPTILE_API_KEY`` from the environment.

    Args:
        repo_name: The GitHub repo in ``owner/repo`` format (e.g.
            ``"acme/api"``). Used by Greptile to index the codebase context.
        diff_text: The raw unified diff string returned by ``get_pr_diff``.

    Returns:
        True if the diff is DB-impacting and should trigger a sqlmap scan,
        False otherwise.
    """
    pass
