"""
Context stream — Greptile API client (sponsor track).

Owned by: Stream 3 (Context)
Do NOT edit this file if you are on the Brain or Muscle stream.
"""

from __future__ import annotations

import logging
import os

import httpx
from dotenv import load_dotenv
from tenacity import (
    retry,
    retry_if_exception,
    stop_after_attempt,
    wait_exponential,
)

load_dotenv()

logger = logging.getLogger(__name__)

_GREPTILE_API = "https://api.greptile.com/v2"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _greptile_headers() -> dict[str, str]:
    """Both Authorization and X-Github-Token are required by the Greptile API."""
    return {
        "Authorization": f"Bearer {os.getenv('GREPTILE_API_KEY', '')}",
        "X-Github-Token": os.getenv("GITHUB_TOKEN", ""),
        "Content-Type": "application/json",
    }


def _is_retryable(exc: BaseException) -> bool:
    if isinstance(exc, httpx.HTTPStatusError):
        return exc.response.status_code in {429, 502, 503}
    return isinstance(exc, (httpx.TimeoutException, httpx.NetworkError))


_retry = retry(
    retry=retry_if_exception(_is_retryable),
    wait=wait_exponential(multiplier=1, min=1, max=10),
    stop=stop_after_attempt(3),
    reraise=True,
)


async def _ensure_repo_indexed(repo_name: str) -> None:
    """
    Submit the repository for indexing if it hasn't been indexed yet.

    Indexing is idempotent — calling this on an already-indexed repo is safe
    and returns quickly. On first run it kicks off async indexing (3-5 min for
    small repos); subsequent calls are instant because Greptile caches the index.
    """
    try:
        @_retry
        async def _index() -> None:
            async with httpx.AsyncClient(timeout=30) as client:
                resp = await client.post(
                    f"{_GREPTILE_API}/repositories",
                    headers=_greptile_headers(),
                    json={
                        "remote": "github",
                        "repository": repo_name,
                        "branch": "main",
                    },
                )
                # 200 = started / already processing; anything else is unexpected
                if resp.status_code not in {200, 201}:
                    logger.warning(
                        "_ensure_repo_indexed got status %s for %s: %s",
                        resp.status_code,
                        repo_name,
                        resp.text[:200],
                    )

        await _index()
    except Exception:
        logger.exception("_ensure_repo_indexed failed for repo=%s", repo_name)


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------


async def analyze_diff_for_db_impact(repo_name: str, diff_text: str) -> bool:
    """
    Classify whether a PR diff touches database code.

    Sends the diff to the Greptile API and returns True if the diff contains
    database-impacting changes — raw SQL queries, ORM model changes, migration
    files, query-builder logic, etc. Returns False if the diff is unrelated to
    the database layer.

    Reads ``GREPTILE_API_KEY`` and ``GITHUB_TOKEN`` from the environment.

    Args:
        repo_name: The GitHub repo in ``owner/repo`` format (e.g.
            ``"acme/api"``). Used by Greptile to index the codebase context.
        diff_text: The raw unified diff string returned by ``get_pr_diff``.

    Returns:
        True if the diff is DB-impacting and should trigger a sqlmap scan,
        False otherwise.
    """
    try:
        # Greptile requires the repo to be indexed before it can be queried.
        # This call is idempotent — fast on subsequent runs once the index exists.
        await _ensure_repo_indexed(repo_name)

        # Strict structured prompt: forces a single-word YES/NO response so
        # parsing is deterministic and cannot false-positive on negative answers
        # that happen to contain DB keywords (e.g. "No sql changes found").
        prompt = (
            "You are a security code reviewer. "
            "Does the following git diff touch database code "
            "(raw SQL queries, ORM queries, schema migrations, or query-builder logic)? "
            "Reply with exactly one word: YES or NO.\n\n"
            f"Repository: {repo_name}\n\nDiff:\n{diff_text}"
        )

        payload = {
            "messages": [{"role": "user", "content": prompt}],
            "repositories": [
                {"remote": "github", "repository": repo_name, "branch": "main"}
            ],
        }

        @_retry
        async def _query() -> bool:
            async with httpx.AsyncClient(timeout=60) as client:
                resp = await client.post(
                    f"{_GREPTILE_API}/query",
                    headers=_greptile_headers(),
                    json=payload,
                )
                resp.raise_for_status()
                data = resp.json()
                answer = data.get("message", "").strip().upper()
                return answer.startswith("YES")

        return await _query()
    except Exception:
        logger.exception(
            "analyze_diff_for_db_impact failed for repo=%s", repo_name
        )
        return False
