"""
Context stream — Nia API client (sponsor track).

Owned by: Stream 3 (Context)
Do NOT edit this file if you are on the Brain or Muscle stream.
"""

from __future__ import annotations


async def get_waf_bypasses(tech_stack: str) -> list[str]:
    """
    Return a list of sqlmap tamper script names suited to the given tech stack.

    Queries the Nia API with the detected tech stack and returns a list of
    tamper script identifiers that sqlmap should use to bypass WAF rules for
    that stack (e.g. ``["space2comment", "between", "randomcase"]``).

    The returned list is stored in ``PRScanState.waf_bypasses`` and passed
    to ``run_sqlmap`` as the ``tamper_script`` argument.

    Reads ``NIA_API_KEY`` from the environment.

    Args:
        tech_stack: A string describing the target's tech stack (e.g.
            ``"python-fastapi-postgres"``). Populated from
            ``PRScanState.tech_stack``.

    Returns:
        A list of sqlmap tamper script names. May be empty if Nia has no
        recommendations for the given stack.
    """
    pass
