"""
Context stream — Nia API client (sponsor track).

Owned by: Stream 3 (Context)
Do NOT edit this file if you are on the Brain or Muscle stream.
"""

from __future__ import annotations

import logging
import os

import httpx
from dotenv import load_dotenv
from tenacity import (
    retry,
    retry_if_exception,
    stop_after_attempt,
    wait_exponential,
)

load_dotenv()

logger = logging.getLogger(__name__)

_NIA_API = "https://api.nia.ac/v1"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _is_retryable(exc: BaseException) -> bool:
    if isinstance(exc, httpx.HTTPStatusError):
        return exc.response.status_code in {429, 502, 503}
    return isinstance(exc, (httpx.TimeoutException, httpx.NetworkError))


_retry = retry(
    retry=retry_if_exception(_is_retryable),
    wait=wait_exponential(multiplier=1, min=1, max=10),
    stop=stop_after_attempt(3),
    reraise=True,
)


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------


async def get_waf_bypasses(tech_stack: str) -> list[str]:
    """
    Return a list of sqlmap tamper script names suited to the given tech stack.

    Queries the Nia API with the detected tech stack and returns a list of
    tamper script identifiers that sqlmap should use to bypass WAF rules for
    that stack (e.g. ``["space2comment", "between", "randomcase"]``).

    The returned list is stored in ``PRScanState.waf_bypasses`` and passed
    to ``run_sqlmap`` as the ``tamper_script`` argument.

    Reads ``NIA_API_KEY`` from the environment.

    Args:
        tech_stack: A string describing the target's tech stack (e.g.
            ``"python-fastapi-postgres"``). Populated from
            ``PRScanState.tech_stack``.

    Returns:
        A list of sqlmap tamper script names. May be empty if Nia has no
        recommendations for the given stack.
    """
    try:
        api_key = os.getenv("NIA_API_KEY", "")
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }

        @_retry
        async def _fetch() -> list[str]:
            async with httpx.AsyncClient(timeout=30) as client:
                resp = await client.post(
                    f"{_NIA_API}/waf-bypasses",
                    headers=headers,
                    json={"tech_stack": tech_stack},
                )
                resp.raise_for_status()
                data = resp.json()
                bypasses = data.get("bypasses", [])
                if not isinstance(bypasses, list):
                    logger.warning(
                        "Nia API returned unexpected bypasses type: %s",
                        type(bypasses).__name__,
                    )
                    return []
                return [str(b) for b in bypasses]

        return await _fetch()
    except Exception:
        logger.exception("get_waf_bypasses failed for tech_stack=%r", tech_stack)
        return []
