"""
Brain stream — agent orchestration and shared state.

Owned by: Stream 1 (Brain)
Do NOT edit this file if you are on the Muscle or Context stream.
"""

from __future__ import annotations

from pydantic import BaseModel


# ---------------------------------------------------------------------------
# Shared State
# ---------------------------------------------------------------------------


class PRScanState(BaseModel):
    """
    Single source of truth for a PR scan run.

    Passed between every LangChain/LangGraph node. All fields except
    ``pr_url`` are optional so partial state is always valid. Nodes must
    read from and write to this model — never pass raw dicts between nodes.
    """

    pr_url: str
    repo_name: str | None = None
    diff_text: str | None = None
    db_impacted: bool | None = None
    """Set by the Greptile node. None means not yet classified."""
    tech_stack: str | None = None
    waf_bypasses: list[str] = []
    """Set by the Nia node. Empty list means not yet fetched."""
    target_url: str | None = None
    sqlmap_result: dict | None = None
    """Set by the Muscle stream's run_sqlmap wrapper."""
    nuclei_result: dict | None = None
    """Set by the Muscle stream's run_nuclei wrapper."""
    simplified_report: str | None = None
    """LLM-generated human-readable summary; posted to the PR."""
    pending_comment_id: int | None = None
    """GitHub comment ID returned by post_pending_status; used by update_pr_comment."""
    bounty_paid: bool = False
    """Set to True after a successful AllScale payout."""


# ---------------------------------------------------------------------------
# Mock fixture — Brain-owned, edit freely for local dev loops
# ---------------------------------------------------------------------------

MOCK_PR_SCAN_STATE = PRScanState(
    pr_url="https://github.com/acme/api/pull/99",
    repo_name="acme/api",
    diff_text=(
        "--- a/app/routes/products.py\n"
        "+++ b/app/routes/products.py\n"
        "@@ -14,7 +14,7 @@ async def search_products(q: str, db: Session = Depends(get_db)):\n"
        '-    results = db.execute("SELECT * FROM products").fetchall()\n'
        '+    results = db.execute(f"SELECT * FROM products WHERE name = \'{q}\'").fetchall()\n'
        "     return results\n"
    ),
    db_impacted=True,
    tech_stack="python-fastapi-postgres",
    target_url="http://localhost:3000/rest/products/search?q=",
    waf_bypasses=["space2comment", "between"],
)
"""
Pre-populated PRScanState used when running ``python main.py --mock``.

Simulates a state where Greptile has already classified the diff as
DB-impacting (a raw f-string SQL injection was introduced). The orchestrator
must skip steps 1–3 and start at step 5 (tool execution + LLM simplify).

Edit this fixture freely to test different scenarios — different tech stacks,
different WAF bypass lists, different raw sqlmap output shapes, etc.
"""


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------


class AegisAgent:
    """
    Orchestrates a full PR vulnerability scan using LangChain/LangGraph.

    Each public method corresponds to a node (or subgraph) in the
    LangGraph workflow. All inter-node data flows through a ``PRScanState``
    instance — never as raw dicts.
    """

    async def process_pull_request(
        self,
        pr_url: str | None = None,
        mock_state: PRScanState | None = None,
    ) -> PRScanState:
        """
        Run a full AegisAgent scan for a Pull Request.

        Live mode (pr_url provided, mock_state=None):
            1. Post a pending-status comment (post_pending_status → comment_id).
            2. Fetch the PR diff (get_pr_diff → diff_text).
            3. Classify DB impact (analyze_diff_for_db_impact → db_impacted).
               If False: edit the pending comment with "No DB impact" and return.
            4. Fetch WAF bypasses (get_waf_bypasses → waf_bypasses).
            5. Run sqlmap + nuclei (run_sqlmap, run_nuclei → results).
            6. Trigger bounty payout if vuln confirmed (trigger_bounty_payout).
            7. Simplify the report (simplify_vulnerability_report).
               Edit the pending comment with the simplified report.

        Mock mode (mock_state provided, pr_url=None):
            Skip steps 1–3. Inject mock_state directly and start at step 5.
            Use this path for LLM prompt iteration (``python main.py --mock``).

        Args:
            pr_url: Full GitHub PR URL. Required in live mode.
            mock_state: Pre-built PRScanState fixture. Required in mock mode.

        Returns:
            The final PRScanState after all nodes have run.
        """
        pass

    async def simplify_vulnerability_report(self, raw_data: dict) -> str:
        """
        Translate raw sqlmap/nuclei output into a human-readable summary.

        Takes the structured dict returned by ``run_sqlmap`` or ``run_nuclei``
        and uses an LLM to produce a concise Markdown summary that a developer
        with no sqlmap experience can understand. The output is what gets posted
        to the PR comment.

        Args:
            raw_data: The dict returned by run_sqlmap or run_nuclei. Must
                include a ``"status"`` key ("success", "timeout", or "error").

        Returns:
            A Markdown-formatted string summarising the vulnerability findings
            (or lack thereof) in plain developer-friendly language.
        """
        pass
