"""
Brain stream — agent orchestration and shared state.

Owned by: Stream 1 (Brain)
Do NOT edit this file if you are on the Muscle or Context stream.
"""

from __future__ import annotations

import asyncio
import json
from typing import TYPE_CHECKING, Any

from pydantic import BaseModel
from langgraph.graph import StateGraph, START, END

if TYPE_CHECKING:
    from core.deps import BrainDeps


# ---------------------------------------------------------------------------
# Shared State
# ---------------------------------------------------------------------------


class PRScanState(BaseModel):
    """
    Single source of truth for a PR scan run.

    Passed between every LangGraph node. All fields except ``pr_url`` are
    optional so partial state is always valid. Nodes must read from and
    write to this model — never pass raw dicts between nodes.
    """

    pr_url: str
    repo_name: str | None = None
    diff_text: str | None = None
    db_impacted: bool | None = None
    """Set by the Greptile node. None means not yet classified."""
    tech_stack: str | None = None
    waf_bypasses: list[str] = []
    """Set by the Nia node. Empty list means not yet fetched."""
    target_url: str | None = None
    sqlmap_result: dict | None = None
    """Set by the Muscle stream's run_sqlmap wrapper."""
    nuclei_result: dict | None = None
    """Set by the Muscle stream's run_nuclei wrapper."""
    simplified_report: str | None = None
    """LLM-generated human-readable summary; posted to the PR."""
    pending_comment_id: int | None = None
    """GitHub comment ID returned by post_pending_status; used by update_pr_comment."""
    bounty_paid: bool = False
    """Set to True after a successful AllScale payout."""
    bounty_wallet: str | None = None
    """Recipient wallet for the AllScale bounty. Sourced from BOUNTY_WALLET env."""
    bounty_amount: float = 100.0
    """Bounty payout amount. Sourced from BOUNTY_AMOUNT env (default 100.0)."""


# ---------------------------------------------------------------------------
# Mock fixture — Brain-owned, edit freely for local dev loops
# ---------------------------------------------------------------------------

MOCK_PR_SCAN_STATE = PRScanState(
    pr_url="https://github.com/acme/api/pull/99",
    repo_name="acme/api",
    diff_text=(
        "--- a/app/routes/products.py\n"
        "+++ b/app/routes/products.py\n"
        "@@ -14,7 +14,7 @@ async def search_products(q: str, db: Session = Depends(get_db)):\n"
        '-    results = db.execute("SELECT * FROM products").fetchall()\n'
        '+    results = db.execute(f"SELECT * FROM products WHERE name = \'{q}\'").fetchall()\n'
        "     return results\n"
    ),
    db_impacted=True,
    tech_stack="python-fastapi-postgres",
    target_url="http://localhost:3000/rest/products/search?q=",
    waf_bypasses=["space2comment", "between"],
    pending_comment_id=1,
    bounty_wallet="0xMOCKWALLET0000000000000000000000000000000",
    bounty_amount=100.0,
)
"""
Pre-populated PRScanState used when running ``python main.py --mock``.

Simulates a state where Greptile has already classified the diff as
DB-impacting (a raw f-string SQL injection was introduced). The orchestrator
skips steps 1–3 and starts at step 5 (tool execution + LLM simplify).

``pending_comment_id`` is set so the mock update-comment stub still runs and
prints the final summary back to the developer iterating on prompts.

Edit this fixture freely to test different scenarios — different tech stacks,
different WAF bypass lists, different raw sqlmap output shapes, etc.
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _parse_repo_name(pr_url: str) -> str:
    """Extract ``owner/repo`` from a GitHub PR URL.

    Example: ``https://github.com/acme/api/pull/99`` -> ``acme/api``.
    """
    parts = pr_url.rstrip("/").split("/")
    if len(parts) < 4:
        return ""
    return f"{parts[-4]}/{parts[-3]}"


def _aggregate_status(sqlmap: dict | None, nuclei: dict | None) -> str:
    """Combine the two scanner statuses into one for the LLM prompt."""
    s_status = (sqlmap or {}).get("status", "error")
    n_status = (nuclei or {}).get("status", "error")
    if s_status == "success" or n_status == "success":
        return "success"
    if s_status == "timeout" or n_status == "timeout":
        return "timeout"
    return "error"


def _extract_text(response: Any) -> str:
    """Pull plain text out of a LangChain AIMessage response."""
    content = getattr(response, "content", response)
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts: list[str] = []
        for part in content:
            if isinstance(part, str):
                parts.append(part)
            elif isinstance(part, dict):
                parts.append(part.get("text", ""))
        return "\n".join(p for p in parts if p)
    return str(content)


_SIMPLIFY_SYSTEM_PROMPT = (
    "You are a senior security engineer. Translate raw sqlmap and nuclei scan "
    "output into a concise Markdown comment for a Pull Request author who has "
    "never seen these tools before. Be specific about what was found (or not), "
    "name the vulnerable parameter or file, and end with one actionable next "
    "step. Stay under 200 words. Use a single H2 header at the top."
)


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------


class AegisAgent:
    """
    Orchestrates a full PR vulnerability scan as a LangGraph state machine.

    The agent depends on Stream 2 and Stream 3 only through a ``BrainDeps``
    container injected at construction time. It never imports from
    ``tools.*`` or ``integrations.*`` directly, which lets Brain run
    end-to-end in ``--mock`` mode regardless of the other streams' progress.

    Two compiled graphs are cached on the instance:

    * ``_live_graph`` — the full 7-step flow starting at ``post_pending``.
    * ``_mock_graph`` — a shortened graph starting at ``run_scans`` for
      LLM prompt iteration with pre-populated state.
    """

    def __init__(self, deps: "BrainDeps") -> None:
        self.deps = deps
        self._live_graph = self._build_live_graph()
        self._mock_graph = self._build_mock_graph()

    # ------------------------------------------------------------------
    # Nodes
    # ------------------------------------------------------------------

    async def _node_post_pending(self, state: PRScanState) -> dict:
        comment_id = await self.deps.post_pending_status(state.pr_url)
        return {
            "pending_comment_id": comment_id,
            "repo_name": _parse_repo_name(state.pr_url),
        }

    async def _node_fetch_diff(self, state: PRScanState) -> dict:
        diff = await self.deps.get_pr_diff(state.pr_url)
        return {"diff_text": diff}

    async def _node_classify_db(self, state: PRScanState) -> dict:
        impacted = await self.deps.analyze_diff_for_db_impact(
            state.repo_name or "", state.diff_text or ""
        )
        return {"db_impacted": impacted}

    async def _node_early_exit_no_db(self, state: PRScanState) -> dict:
        body = (
            "## AegisAgent\n\n"
            "No database-impacting changes detected in this PR. "
            "Skipping deep scan."
        )
        if state.pending_comment_id is not None:
            await self.deps.update_pr_comment(state.pending_comment_id, body)
        return {"simplified_report": body}

    async def _node_fetch_waf(self, state: PRScanState) -> dict:
        bypasses = await self.deps.get_waf_bypasses(state.tech_stack or "")
        return {"waf_bypasses": bypasses}

    async def _node_run_scans(self, state: PRScanState) -> dict:
        tamper = ",".join(state.waf_bypasses) if state.waf_bypasses else None
        target = state.target_url or ""
        sqlmap_task = self.deps.run_sqlmap(target, tamper)
        nuclei_task = self.deps.run_nuclei(target)
        sqlmap_result, nuclei_result = await asyncio.gather(
            sqlmap_task, nuclei_task
        )
        return {
            "sqlmap_result": sqlmap_result,
            "nuclei_result": nuclei_result,
        }

    async def _node_bounty(self, state: PRScanState) -> dict:
        sqlmap = state.sqlmap_result or {}
        has_findings = (
            sqlmap.get("status") == "success"
            and bool(sqlmap.get("findings"))
        )
        if has_findings and state.bounty_wallet:
            paid = await self.deps.trigger_bounty_payout(
                state.bounty_wallet, state.bounty_amount
            )
            return {"bounty_paid": paid}
        return {"bounty_paid": False}

    async def _node_simplify_and_post(self, state: PRScanState) -> dict:
        combined = {
            "status": _aggregate_status(state.sqlmap_result, state.nuclei_result),
            "sqlmap": state.sqlmap_result,
            "nuclei": state.nuclei_result,
            "pr_url": state.pr_url,
            "bounty_paid": state.bounty_paid,
            "diff_excerpt": (state.diff_text or "")[:600],
        }
        summary = await self.simplify_vulnerability_report(combined)
        if state.pending_comment_id is not None:
            await self.deps.update_pr_comment(state.pending_comment_id, summary)
        return {"simplified_report": summary}

    # ------------------------------------------------------------------
    # Conditional router
    # ------------------------------------------------------------------

    def _route_after_classify(self, state: PRScanState) -> str:
        return "fetch_waf" if state.db_impacted else "early_exit_no_db"

    # ------------------------------------------------------------------
    # Graph builders
    # ------------------------------------------------------------------

    def _build_live_graph(self):
        g = StateGraph(PRScanState)
        g.add_node("post_pending", self._node_post_pending)
        g.add_node("fetch_diff", self._node_fetch_diff)
        g.add_node("classify_db", self._node_classify_db)
        g.add_node("early_exit_no_db", self._node_early_exit_no_db)
        g.add_node("fetch_waf", self._node_fetch_waf)
        g.add_node("run_scans", self._node_run_scans)
        g.add_node("bounty_payout", self._node_bounty)
        g.add_node("simplify_and_post", self._node_simplify_and_post)

        g.add_edge(START, "post_pending")
        g.add_edge("post_pending", "fetch_diff")
        g.add_edge("fetch_diff", "classify_db")
        g.add_conditional_edges(
            "classify_db",
            self._route_after_classify,
            {
                "fetch_waf": "fetch_waf",
                "early_exit_no_db": "early_exit_no_db",
            },
        )
        g.add_edge("fetch_waf", "run_scans")
        g.add_edge("run_scans", "bounty_payout")
        g.add_edge("bounty_payout", "simplify_and_post")
        g.add_edge("simplify_and_post", END)
        g.add_edge("early_exit_no_db", END)
        return g.compile()

    def _build_mock_graph(self):
        g = StateGraph(PRScanState)
        g.add_node("run_scans", self._node_run_scans)
        g.add_node("bounty_payout", self._node_bounty)
        g.add_node("simplify_and_post", self._node_simplify_and_post)

        g.add_edge(START, "run_scans")
        g.add_edge("run_scans", "bounty_payout")
        g.add_edge("bounty_payout", "simplify_and_post")
        g.add_edge("simplify_and_post", END)
        return g.compile()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def process_pull_request(
        self,
        pr_url: str | None = None,
        mock_state: PRScanState | None = None,
    ) -> PRScanState:
        """
        Run a full AegisAgent scan for a Pull Request.

        Live mode (pr_url provided, mock_state=None):
            Runs the full 7-step graph starting with ``post_pending_status``.
            On a "no DB impact" classification the graph short-circuits to
            ``early_exit_no_db`` and edits the pending comment with a "no
            impact" message.

        Mock mode (mock_state provided):
            Runs the short 3-node graph starting at ``run_scans``. Use this
            for prompt iteration (``python main.py --mock``).

        Args:
            pr_url: Full GitHub PR URL. Required in live mode.
            mock_state: Pre-built PRScanState fixture. Required in mock mode.

        Returns:
            The final PRScanState after all nodes have run.
        """
        if mock_state is not None:
            result = await self._mock_graph.ainvoke(mock_state)
        else:
            if pr_url is None:
                raise ValueError(
                    "process_pull_request requires either pr_url or mock_state"
                )
            import os

            initial = PRScanState(
                pr_url=pr_url,
                bounty_wallet=os.getenv("BOUNTY_WALLET"),
                bounty_amount=float(os.getenv("BOUNTY_AMOUNT", "100.0")),
            )
            result = await self._live_graph.ainvoke(initial)

        if isinstance(result, PRScanState):
            return result
        return PRScanState.model_validate(result)

    async def simplify_vulnerability_report(self, raw_data: dict) -> str:
        """
        Translate raw sqlmap/nuclei output into a human-readable summary.

        The orchestrator calls this with a combined payload of the form::

            {
                "status": "success" | "timeout" | "error",
                "sqlmap": <run_sqlmap dict or None>,
                "nuclei": <run_nuclei dict or None>,
                "pr_url": str,
                "bounty_paid": bool,
                "diff_excerpt": str,
            }

        Args:
            raw_data: Combined scan payload as described above. ``status``
                drives prompt phrasing (success vs timeout vs error).

        Returns:
            A Markdown-formatted string ready to post as a PR comment.
        """
        from langchain_core.messages import HumanMessage, SystemMessage

        status = raw_data.get("status", "unknown")
        if status == "timeout":
            instruction = (
                "Both or one of the scans timed out at the 60-second kill "
                "switch. Write a comment explaining the scan was inconclusive "
                "and recommend running it locally with a longer timeout."
            )
        elif status == "error":
            instruction = (
                "The scans errored out. Briefly note that no conclusive result "
                "is available and recommend manual review of the diff excerpt."
            )
        else:
            instruction = (
                "Summarize the findings. If sqlmap detected an injection point, "
                "name the parameter and DBMS and give one remediation sentence. "
                "If nuclei reported anything, mention it. If neither found "
                "anything, say so clearly. Mention bounty payout status if a "
                "bounty was paid."
            )

        payload = json.dumps(raw_data, indent=2, default=str)
        messages = [
            SystemMessage(content=_SIMPLIFY_SYSTEM_PROMPT),
            HumanMessage(
                content=f"{instruction}\n\nScan data:\n```json\n{payload}\n```"
            ),
        ]
        response = await self.deps.llm.ainvoke(messages)
        return _extract_text(response)
