"""
Brain stream — scenario fixtures for ``python main.py --mock --scenario X``.

Owned by: Stream 1 (Brain)
Do NOT edit this file if you are on the Muscle or Context stream.

Each ``Scenario`` bundles the pre-built ``PRScanState`` (or ``pr_url``) and a
``BrainDeps`` factory tuned to exercise a specific code path. The CLI in
``main.py`` looks up scenarios by name from ``SCENARIOS``.

Scenarios that set ``mock_state`` run the agent's short 3-node mock graph
(``run_scans → bounty_payout → simplify_and_post``). Scenarios that set
``pr_url`` run the full 8-node live graph from START — useful for exercising
the early-exit branch and the first four nodes (``post_pending``, ``fetch_diff``,
``classify_db``, ``fetch_waf``).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

from core.agent import MOCK_PR_SCAN_STATE, PRScanState
from core.deps import BrainDeps, build_mock_deps


# ---------------------------------------------------------------------------
# Scenario container
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Scenario:
    """One named test fixture for the ``--scenario`` CLI flag.

    Exactly one of ``mock_state`` / ``pr_url`` must be set:

    * ``mock_state`` -> run the mock 3-node graph with this state.
    * ``pr_url``     -> run the full 8-node live graph with mocked deps.
    """

    name: str
    description: str
    deps_factory: Callable[[], BrainDeps]
    mock_state: PRScanState | None = None
    pr_url: str | None = None

    def __post_init__(self) -> None:
        if (self.mock_state is None) == (self.pr_url is None):
            raise ValueError(
                f"Scenario {self.name!r} must set exactly one of "
                "mock_state / pr_url"
            )


# ---------------------------------------------------------------------------
# Canned scanner results for the timeout / error / clean variants
# ---------------------------------------------------------------------------


_TIMEOUT_RESULT = {
    "status": "timeout",
    "stdout": "",
    "stderr": "killed after 60s",
    "findings": [],
}

_ERROR_RESULT = {
    "status": "error",
    "stdout": "",
    "stderr": "sqlmap: command not found",
    "findings": [],
}

_CLEAN_SQLMAP_RESULT = {
    "status": "success",
    "stdout": "[INFO] no injection points identified\n",
    "stderr": "",
    "findings": [],
}


# ---------------------------------------------------------------------------
# Deps factories per scenario
# ---------------------------------------------------------------------------


def _vuln_deps() -> BrainDeps:
    return build_mock_deps()


def _clean_deps() -> BrainDeps:
    return build_mock_deps(sqlmap_result=_CLEAN_SQLMAP_RESULT)


def _timeout_deps() -> BrainDeps:
    return build_mock_deps(
        sqlmap_result=_TIMEOUT_RESULT,
        nuclei_result=_TIMEOUT_RESULT,
    )


def _error_deps() -> BrainDeps:
    return build_mock_deps(
        sqlmap_result=_ERROR_RESULT,
        nuclei_result=_ERROR_RESULT,
    )


def _no_db_impact_deps() -> BrainDeps:
    return build_mock_deps(db_impacted=False)


# ---------------------------------------------------------------------------
# Scenario registry
# ---------------------------------------------------------------------------


SCENARIOS: dict[str, Scenario] = {
    "vuln": Scenario(
        name="vuln",
        description=(
            "DB-impacting PR; sqlmap finds an injection point; bounty paid; "
            "summary describes the vulnerability. Mock graph (3 nodes)."
        ),
        deps_factory=_vuln_deps,
        mock_state=MOCK_PR_SCAN_STATE,
    ),
    "clean": Scenario(
        name="clean",
        description=(
            "DB-impacting PR; scans run successfully but find nothing; no "
            "bounty paid; summary says 'all clear'. Mock graph (3 nodes)."
        ),
        deps_factory=_clean_deps,
        mock_state=MOCK_PR_SCAN_STATE,
    ),
    "timeout": Scenario(
        name="timeout",
        description=(
            "Both scanners hit the 60s kill switch. Exercises the timeout "
            "branch in simplify_vulnerability_report. Mock graph (3 nodes)."
        ),
        deps_factory=_timeout_deps,
        mock_state=MOCK_PR_SCAN_STATE,
    ),
    "error": Scenario(
        name="error",
        description=(
            "Both scanners fail to start. Exercises the error branch in "
            "simplify_vulnerability_report. Mock graph (3 nodes)."
        ),
        deps_factory=_error_deps,
        mock_state=MOCK_PR_SCAN_STATE,
    ),
    "no_db_impact": Scenario(
        name="no_db_impact",
        description=(
            "Greptile says the diff doesn't touch DB code; agent posts a "
            "'no impact' comment and exits. Live graph from START — "
            "exercises post_pending, fetch_diff, classify_db, and the "
            "conditional edge to early_exit_no_db (8 of 8 nodes wired)."
        ),
        deps_factory=_no_db_impact_deps,
        pr_url="https://github.com/acme/api/pull/1",
    ),
}


def get_scenario(name: str) -> Scenario:
    """Look up a scenario by name. Raises KeyError with the valid set."""
    try:
        return SCENARIOS[name]
    except KeyError:
        valid = ", ".join(sorted(SCENARIOS.keys()))
        raise KeyError(
            f"Unknown scenario {name!r}. Valid scenarios: {valid}"
        ) from None
