"""
Muscle stream — async nuclei subprocess wrapper.

Owned by: Stream 2 (Muscle)
Do NOT edit this file if you are on the Brain or Context stream.
"""

from __future__ import annotations


async def run_nuclei(target_url: str) -> dict:
    """
    Run nuclei against the given URL and return structured results.

    Spawns nuclei as an async subprocess via ``asyncio.create_subprocess_exec``
    and enforces a hard 60-second timeout with ``asyncio.wait_for``. If the
    process does not complete in time it is terminated/killed and a timeout
    dict is returned — never raises.

    Return dict shapes:

        Success:
            {"status": "success", "target": target_url,
             "stdout": "<raw output>", "stderr": "", "findings": []}

        Timeout (kill switch triggered):
            {"status": "timeout", "target": target_url,
             "stdout": "", "stderr": "killed after 60s"}

        Error:
            {"status": "error", "target": target_url,
             "stdout": "", "stderr": "<error message>"}

    The Brain stream reads ``result["status"]`` to decide next steps and
    will NEVER try/except around this function — handle all failure modes
    here and always return one of the three shapes above.

    Args:
        target_url: The URL to scan with nuclei templates (e.g.
            "http://target/rest/products/search?q=").

    Returns:
        A dict with keys ``status``, ``target``, ``stdout``, ``stderr``,
        and optionally ``findings``.
    """
    pass
