"""
Muscle stream — async nuclei subprocess wrapper.

Owned by: Stream 2 (Muscle)
Do NOT edit this file if you are on the Brain or Context stream.
"""

from __future__ import annotations

import asyncio
import json
import shutil

from rich.console import Console

console = Console()


async def run_nuclei(target_url: str) -> dict:
    """
    Run nuclei against the given URL and return structured results.

    Spawns nuclei as an async subprocess via ``asyncio.create_subprocess_exec``
    and enforces a hard 120-second timeout with ``asyncio.wait_for``. If the
    process does not complete in time it is terminated/killed and a timeout
    dict is returned — never raises.

    nuclei is invoked with ``-exclude-tags sqli`` on every call — sqlmap owns
    that lane. No ``-tags`` whitelist is applied so the full template library
    is available.

    Return dict shapes:

        Success:
            {"status": "success", "target": target_url,
             "stdout": "<raw output>", "stderr": "", "findings": [...]}

        Timeout (kill switch triggered):
            {"status": "timeout", "target": target_url,
             "stdout": "", "stderr": "killed after 120s"}

        Error:
            {"status": "error", "target": target_url,
             "stdout": "", "stderr": "<error message>"}

    The Brain stream reads ``result["status"]`` to decide next steps and
    will NEVER try/except around this function — handle all failure modes
    here and always return one of the three shapes above.

    Args:
        target_url: The URL to scan with nuclei templates.

    Returns:
        A dict with keys ``status``, ``target``, ``stdout``, ``stderr``,
        and optionally ``findings``.
    """
    if not shutil.which("nuclei"):
        return {"status": "error", "target": target_url, "stdout": "",
                "stderr": "nuclei not found on PATH — install before running scans"}

    cmd = [
        "nuclei", "-u", target_url,
        "-exclude-tags", "sqli",
        "-json",
    ]

    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
    except Exception as exc:
        return {"status": "error", "target": target_url, "stdout": "", "stderr": str(exc)}

    try:
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=120)
        raw = stdout.decode()
        return {
            "status": "success",
            "target": target_url,
            "stdout": raw,
            "stderr": stderr.decode(),
            "findings": _parse_nuclei_findings(raw),
        }
    except asyncio.TimeoutError:
        proc.terminate()
        try:
            await asyncio.wait_for(proc.wait(), timeout=2)
        except asyncio.TimeoutError:
            proc.kill()
            await proc.wait()
        console.log(f"[yellow]nuclei timed out on {target_url} — scan inconclusive[/yellow]")
        return {"status": "timeout", "target": target_url, "stdout": "", "stderr": "killed after 120s"}
    except Exception as exc:
        return {"status": "error", "target": target_url, "stdout": "", "stderr": str(exc)}


def _parse_nuclei_findings(stdout: str) -> list[dict]:
    findings = []
    for line in stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        info = entry.get("info", {})
        tags = info.get("tags", [])
        findings.append({
            "type": tags[0] if tags else "unknown",
            "template_id": entry.get("template-id", ""),
            "severity": info.get("severity", "info"),
            "name": info.get("name", ""),
        })
    return findings
