"""
Muscle stream — async sqlmap subprocess wrapper.

Owned by: Stream 2 (Muscle)
Do NOT edit this file if you are on the Brain or Context stream.
"""

from __future__ import annotations

import asyncio
import re
import shutil

from rich.console import Console

console = Console()


async def run_sqlmap(
    target_url: str,
    tamper_script: str | None = None,
    post_data: str | None = None,
    cookie: str | None = None,
    headers: dict[str, str] | None = None,
) -> dict:
    """
    Run sqlmap against the given URL and return structured results.

    Spawns sqlmap as an async subprocess via ``asyncio.create_subprocess_exec``
    and enforces a hard 60-second timeout with ``asyncio.wait_for``. If the
    process does not complete in time it is terminated/killed and a timeout
    dict is returned — never raises.

    Return dict shapes:

        Success:
            {"status": "success", "target": target_url,
             "stdout": "<raw output>", "stderr": "", "findings": [...]}

        Timeout (kill switch triggered):
            {"status": "timeout", "target": target_url,
             "stdout": "", "stderr": "killed after 60s"}

        Error:
            {"status": "error", "target": target_url,
             "stdout": "", "stderr": "<error message>"}

    The Brain stream reads ``result["status"]`` to decide next steps and
    will NEVER try/except around this function — handle all failure modes
    here and always return one of the three shapes above.

    Args:
        target_url: The URL to test for SQL injection.
        tamper_script: Optional sqlmap tamper script name (e.g. "space2comment").
        post_data: Optional POST body string (e.g. "id=1&name=foo"). When
            provided, sqlmap probes POST parameters instead of GET.
        cookie: Optional cookie header string (e.g. "session=abc123").
        headers: Optional dict of extra HTTP headers to inject.

    Returns:
        A dict with keys ``status``, ``target``, ``stdout``, ``stderr``,
        and optionally ``findings``.
    """
    if not shutil.which("sqlmap"):
        return {"status": "error", "target": target_url, "stdout": "",
                "stderr": "sqlmap not found on PATH — install before running scans"}

    cmd = [
        "sqlmap", "-u", target_url,
        "--batch", "--level=3", "--risk=2", "--technique=BEUSTQ",
    ]
    if tamper_script:
        cmd += ["--tamper", tamper_script]
    if post_data:
        cmd += ["--data", post_data]
    if cookie:
        cmd += ["--cookie", cookie]
    if headers:
        for key, value in headers.items():
            cmd += ["-H", f"{key}: {value}"]

    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
    except Exception as exc:
        return {"status": "error", "target": target_url, "stdout": "", "stderr": str(exc)}

    try:
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=60)
        raw = stdout.decode()
        findings = _parse_sqlmap_findings(raw)
        if proc.returncode != 0 and not findings:
            return {
                "status": "error",
                "target": target_url,
                "stdout": raw,
                "stderr": stderr.decode(),
            }
        return {
            "status": "success",
            "target": target_url,
            "stdout": raw,
            "stderr": stderr.decode(),
            "findings": findings,
        }
    except asyncio.TimeoutError:
        proc.terminate()
        try:
            await asyncio.wait_for(proc.wait(), timeout=2)
        except asyncio.TimeoutError:
            proc.kill()
            await proc.wait()
        console.log(f"[yellow]sqlmap timed out on {target_url} — scan inconclusive[/yellow]")
        return {"status": "timeout", "target": target_url, "stdout": "", "stderr": "killed after 60s"}
    except Exception as exc:
        return {"status": "error", "target": target_url, "stdout": "", "stderr": str(exc)}


def _parse_sqlmap_findings(stdout: str) -> list[dict]:
    findings = []
    # sqlmap reports injectable params in lines like:
    # Parameter: id (GET) ... Type: Boolean-based blind ... DBMS: MySQL
    param_pattern = re.compile(r"Parameter:\s+(\S+)")
    technique_pattern = re.compile(
        r"Type:\s+(Boolean-based blind|Error-based|UNION query|Stacked queries|Time-based blind|Inline queries)"
    )
    db_pattern = re.compile(r"back-end DBMS:\s+(.+)", re.IGNORECASE)

    technique_map = {
        "Boolean-based blind": "B",
        "Error-based": "E",
        "UNION query": "U",
        "Stacked queries": "S",
        "Time-based blind": "T",
        "Inline queries": "Q",
    }

    params = param_pattern.findall(stdout)
    techniques = technique_pattern.findall(stdout)
    db_match = db_pattern.search(stdout)
    db = db_match.group(1).strip() if db_match else "unknown"

    for param, technique in zip(params, techniques):
        findings.append({
            "type": "sqli",
            "technique": technique_map.get(technique, technique),
            "parameter": param,
            "db": db,
        })

    return findings
